
name: Build, Scan, and Deploy React App to Azure Container Apps

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run SonarQube Scan
      env:
        SONAR_HOST_URL: ${{  http://74.225.164.197:9000  }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        npx sonar-scanner \
          -Dsonar.projectKey=sarasai-manual \
          -Dsonar.sources=. \
          -Dsonar.host.url=${{ http://74.225.164.197:9000 }} \
          -Dsonar.login=${{ sqp_ecd91d5635329858b65caaa7acb13555092395a4 }}

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to ACR
      run: |
        az acr login --name ${{ secrets.ACR_NAME }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/frontend:latest .

    - name: Push Docker image to ACR
      run: |
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/frontend:latest

    - name: Deploy to Azure Container Apps
      run: |
        az containerapp update \
          --name ${{ secrets.CONTAINER_APP_NAME }} \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --environment ${{ secrets.ENVIRONMENT_NAME }} \
          --image ${{ secrets.ACR_NAME }}.azurecr.io/frontend:latest
